language: php
sudo: false
dist: trusty

env:
  global:
    - RUN_PHPCS="no"
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.3
      dist: precise
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: RUN_PHPCS="yes" RUN_SCRUTINIZER="yes" PHPUNIT_FLAGS="--coverage-clover .travis/logs/clover.xml"
    - php: 7.0
    - php: 7.0
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: nightly

before_script:
  - composer self-update
  - if [ "RUN_SCRUTINIZER" == "yes" ]; then composer require --no-update satooshi/php-coveralls:dev-master --prefer-source; fi
  - composer update $COMPOSER_FLAGS

script:
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then mkdir -p .travis/logs; fi
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover .travis/logs/clover.xml; fi
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml src/; fi;

after_script:
  - php vendor/bin/coveralls -v
